# Generated by Django 4.1.13 on 2024-05-29 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=50)),
                ('preco', models.IntegerField()),
                ('imagem', models.URLField()),
                ('ano', models.IntegerField()),
            ],
        ),
    ]
