# Generated by Django 4.1.13 on 2024-05-29 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='celular',
            options={'verbose_name': 'Celular', 'verbose_name_plural': 'Celulares'},
        ),
        migrations.AlterField(
            model_name='celular',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='celular',
            name='imagem',
            field=models.URLField(max_length=300),
        ),
    ]
